[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutron = { path = "../../" }
pulsar = "6.1.0"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "time"] }
